"""Collect per-dataset metrics.json files into one paper-ready summary.

Outputs (under --results-root):
    summary.csv  - one row per dataset (machine-readable)
    summary.tex  - a booktabs LaTeX table comparing our fine-tuned Llama vs. paper SOTA

Run after all per-dataset runs finish:

    python -m app.aggregate --results-root /path/to/results
"""

from __future__ import annotations

import argparse
import glob
import os

from .config import DATASETS
from .utils import LOGGER, load_json

# Map a paper SOTA metric label to the key of the comparable metric we computed, so the
# "ours" column is apples-to-apples with the paper's reported number where possible.
_PAPER_TO_OURS = {
    "Micro-F1": ["entity_micro_f1", "micro_f1"],
    "Macro-F1": ["macro_f1", "entity_macro_f1"],
    "Accuracy": ["accuracy"],
    "F1": ["squad_f1", "micro_f1", "macro_f1"],
    "ROUGE-L": ["rougeL"],
    "ROUGE-2": ["rouge2"],
    "ROUGE-1": ["rouge1"],
}


def _ours_comparable(metrics: dict, paper_metric: str | None) -> tuple[str, float | None]:
    """Return (metric_key_used, value) matching the paper metric when we have it."""
    if paper_metric:
        for key in _PAPER_TO_OURS.get(paper_metric, []):
            if metrics.get(key) is not None:
                return key, float(metrics[key])
    # fall back to the dataset's designated primary metric
    pk = metrics.get("primary_metric")
    if pk and metrics.get(pk) is not None:
        return pk, float(metrics[pk])
    return (pk or "n/a"), None


def _pct(x: float | None) -> str:
    return f"{100 * x:.2f}" if x is not None else "--"


def _tex_escape(s: str) -> str:
    """Escape LaTeX special characters so table cells compile (e.g. extractive_qa)."""
    repl = {
        "&": r"\&", "%": r"\%", "_": r"\_", "#": r"\#", "$": r"\$",
        "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}", "^": r"\textasciicircum{}",
    }
    return "".join(repl.get(c, c) for c in (s or ""))


def collect(results_root: str) -> list[dict]:
    rows = []
    found = {}
    for path in glob.glob(os.path.join(results_root, "*", "metrics.json")):
        try:
            data = load_json(path)
            found[data.get("dataset")] = data
        except Exception as exc:  # pragma: no cover
            LOGGER.warning("Skipping unreadable %s (%s)", path, exc)

    # iterate registry order so the table is grouped by task category
    for stem, spec in DATASETS.items():
        data = found.get(stem)
        if not data:
            continue
        metrics = data.get("metrics", {})
        paper = data.get("paper_sota") or {}
        paper_metric = paper.get("metric")
        ours_key, ours_val = _ours_comparable(metrics, paper_metric)
        rows.append(
            {
                "dataset": stem,
                "display": spec.display,
                "task_type": spec.task_type,
                "our_metric": ours_key,
                "our_score": ours_val,
                "paper_metric": paper_metric,
                "paper_sota": paper.get("value"),
                "paper_method": paper.get("method"),
                "num_eval": metrics.get("num_eval"),
                "bertscore_f1": metrics.get("bertscore_f1"),
                "wall_time_sec": data.get("wall_time_sec"),
                "all_metrics": {k: v for k, v in metrics.items()
                                if k not in ("primary_metric", "primary_score")},
            }
        )
    return rows


def write_csv(rows: list[dict], path: str) -> None:
    import csv

    cols = ["dataset", "display", "task_type", "our_metric", "our_score",
            "paper_metric", "paper_sota", "paper_method", "bertscore_f1",
            "num_eval", "wall_time_sec"]
    with open(path, "w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=cols)
        w.writeheader()
        for r in rows:
            w.writerow({c: r.get(c) for c in cols})


def write_latex(rows: list[dict], path: str, model_label: str) -> None:
    lines = [
        "% Auto-generated by app/aggregate.py — fine-tuned Llama vs. survey SOTA.",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Reproducibility results: " + _tex_escape(model_label) +
        " (LoRA, natural-language prompts) fine-tuned once per dataset, "
        "compared with the best result reported in the survey. "
        "Metrics are matched to the survey's reported metric where possible; "
        "SOTA systems often use a different paradigm and are shown for context only.}",
        "\\label{tab:repro_results}",
        "\\small",
        "\\begin{tabular}{lllcc}",
        "\\toprule",
        "Dataset & Task & Metric & " + _tex_escape(model_label) + " & Survey SOTA (method) \\\\",
        "\\midrule",
    ]
    for r in rows:
        sota = _pct(r["paper_sota"])
        method = _tex_escape(r["paper_method"] or "")
        sota_cell = f"{sota} ({method})" if r["paper_sota"] is not None else "--"
        metric_name = _tex_escape(r["paper_metric"] or r["our_metric"])
        display = _tex_escape(r["display"])
        task = _tex_escape(r["task_type"])
        lines.append(
            f"{display} & {task} & {metric_name} & "
            f"{_pct(r['our_score'])} & {sota_cell} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def print_table(rows: list[dict]) -> None:
    LOGGER.info("%-32s %-14s %-12s %8s %10s", "Dataset", "Metric", "Task", "Ours", "SOTA")
    LOGGER.info("-" * 80)
    for r in rows:
        LOGGER.info(
            "%-32s %-14s %-12s %8s %10s",
            r["display"][:32],
            (r["paper_metric"] or r["our_metric"])[:14],
            r["task_type"][:12],
            _pct(r["our_score"]),
            _pct(r["paper_sota"]),
        )


def main(argv: list[str] | None = None) -> None:
    p = argparse.ArgumentParser(description="Aggregate per-dataset results into a summary.")
    p.add_argument("--results-root", default="results")
    p.add_argument("--model-label", default="Llama-3.1-8B (ours)",
                   help="Column header / caption label for our model.")
    args = p.parse_args(argv)

    rows = collect(args.results_root)
    if not rows:
        LOGGER.warning("No metrics.json found under %s. Run app.run first.", args.results_root)
        return

    csv_path = os.path.join(args.results_root, "summary.csv")
    tex_path = os.path.join(args.results_root, "summary.tex")
    write_csv(rows, csv_path)
    write_latex(rows, tex_path, args.model_label)
    print_table(rows)
    LOGGER.info("Wrote %s and %s (%d datasets).", csv_path, tex_path, len(rows))


if __name__ == "__main__":
    main()
